### ISSUE TITLE
Feature request - linking Meditation pads to bed

### ISSUE THREAD

**Issue by mq2195** [emipa606/StarWarsTheForce#2]
The same way as in mod "Dubs Bad Hygiene" the sinks, toilets and showers are linked to bed (in private bathroom). As a result only owner of the bed is using linked buildings/furniture.

This would be for:
Meditation pad (Jedi)
Meditation pad (Sith)

**Comment by emipa606** [comment]
A bit risky as it may cause issues for those that what universal pads.
You could try [This Is Mine](https://steamcommunity.com/sharedfiles/filedetails/?id=2560584629),  havent tried it but it should be able to set owner for most furniture.
